### ISSUE TITLE
runtime error, please help

### ISSUE THREAD

**Issue by okilimu** [tmpsantos/IBGETools#10]
I downloaded your example pdf-zip and i get this error

openstreetmap@nb11:~/software/IBGETools/out$ ../ibgetools -v --tiles --id parademinas ../../osm/3147105/MSU/
parademinas [Debug] Processing: ../../osm/3147105/MSU/314710505000030/A3/314710505000030.pdf
parademinas [Debug] Processing: ../../osm/3147105/MSU/314710505000015/A2/314710505000015.pdf
Traceback (most recent call last):
  File "../ibgetools", line 155, in <module>
    Main()
  File "../ibgetools", line 140, in Main
    for ibge_map in executor.map(ProcessMap, executor_args):
  File "/usr/lib/pymodules/python2.7/concurrent/futures/_base.py", line 550, in map
    yield future.result()
  File "/usr/lib/pymodules/python2.7/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/lib/pymodules/python2.7/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
TypeError: width must be a natural number, not None
parademinas [Debug] Processing: ../../osm/3147105/MSU/314710505000061/A1/314710505000061.pdf
parademinas [Debug] Processing: ../../osm/3147105/MSU/314710505000118/A4/314710505000118.pdf

Can you help me?
I installed everything, except \* TileMill (for --tiles only)

**Comment by tmpsantos** [comment]
Hi,

The traceback doesn't say much because the script is using python-concurrent (even when the number of jobs is 1). I just fixed that.

Do you mind updating to the latest version and running this batch again with the exact same parameters? We shall see now a more informative error message.

**Comment by okilimu** [comment]
Hello,
this is the new run result

openstreetmap@nb11:~/software/IBGETools/out$ ../ibgetools -v --jobs 1 --kml --id parademinas  ../../osm/3147105/MSU/
parademinas [Debug] Processing: ../../osm/3147105/MSU/314710505000030/A3/314710505000030.pdf
Traceback (most recent call last):
  File "../ibgetools", line 160, in <module>
    Main()
  File "../ibgetools", line 140, in Main
    ibge_map = ProcessMap(param)
  File "../ibgetools", line 54, in ProcessMap
    ibge_map = GetMapFromPath(id, map_path)
  File "../ibgetools", line 28, in GetMapFromPath
    ibge_map = MapFactory(map_path)
  File "/home/openstreetmap/software/IBGETools/IBGETools/Map.py", line 455, in MapFactory
    return map_class(_MakePPMImage(width, height, data), map_path)
  File "/home/openstreetmap/software/IBGETools/IBGETools/Map.py", line 374, in _MakePPMImage
    image = Image()
  File "/usr/lib/python2.7/dist-packages/wand/image.py", line 391, in __init__
    repr(width))
TypeError: width must be a natural number, not None

Greetings Dietmar

**Comment by tmpsantos** [comment]
I'm failing to reproduce the error here, but by the backtrace looks like there is an error when parsing the PDF. At this step, the script is extracting the PPM image from the PDF. Editing the PDF on a text editor, we must see the property "Width" at the object 6.

Two things are coming to my mind:
1. The PDF might be corrupted (very unlikely, but easy to check). Try opening  `../../osm/3147105/MSU/314710505000030/A3/314710505000030.pdf` on evince or any other PDF viewer.
2. Something wrong with python-pdfminer or python-wand
   The versions I have installed here are:

```
python-pdfminer 20110515+dfsg-1
python-wand 0.3.2-1
```

To be honest, I've never tried this script elsewhere other than an Ubuntu 13.10 64-bits (although I don´t see why it should not work on different configurations). Is that your setup? :)

**Comment by okilimu** [comment]
the pdf file is readable.
i have ubuntu 13.04 (raring)
python-pdfminer is identical:Version: 20110515+dfsg-1
but python-wand is older: Version: 0.2.3-1, but seems the newest one available via sudo apt-get
b.t.w. python is version 2.7.1

edit: inside pdf-file:
..
endobj
6 0 obj
<<
/Width 3508
/Subtype/Image
/ColorSpace/DeviceRGB
/Height 4961
/Length 387668
/BitsPerComponent 8
/Interpolate true
/Filter/FlateDecode
/Type/XObject

> > stream
> > (((following binary chars)))

**Comment by tmpsantos** [comment]
> endobj
> 6 0 obj
> <<
> /Width 3508
> /Subtype/Image
> /ColorSpace/DeviceRGB
> /Height 4961
> /Length 387668

Everything seems just fine. Can you try with a newer python-wand? I'm really out of ideas here. :(

BTW, this announcement here might interest you (has an english transcript):
https://lists.openstreetmap.org/pipermail/talk-br/2014-April/006917.html

**Comment by okilimu** [comment]
I'm not so deep in ubuntu and python to make the update, but i will ask my osm collegue to help me, thanks a lot!
Thank you for the message link, too.
I will inform you about the try, but it will take a few days, i think.
