### ISSUE TITLE
Support parallel imaging processing

### ISSUE THREAD

**Issue by tmpsantos** [tmpsantos/IBGETools#2]
Use all the available cores (and not just one) to process the images.

**Comment by tmpsantos** [comment]
Implemented.

**Comment by alexandre-mbm** [comment]
Tip: You can to reference GitHub issues in the commit messages. Write as: `closes #n`, `close #n`, `fixes #n`, `fix #n`. Where "**n**" is the issue number.

**Comment by tmpsantos** [comment]
> Tip: You can to reference GitHub issues in the commit messages. Write as: closes #n, close #n, fixes #n, fix #n. Where "n" is the issue number.

:astonished: Gonna do that next time!
