### ISSUE TITLE
For easy downloading of IBGE's maps files

### ISSUE THREAD

**Issue by alexandre-mbm** [tmpsantos/IBGETools#3]
Your tips about IBGE's FTP files led me to "[bases e referenciais](http://mapas.ibge.gov.br/bases-e-referenciais)" and "[interativos»
arquivos](http://mapas.ibge.gov.br/interativos/arquivos)" IBGE maps.

There is a [Python code](http://www.buscarcep.com.br/exemplos/buscar_cep_python.zip) by [Daniel Gonçalves](mailto:daniel@base4.com.br) that query and parse or use the [BuscarCep.com.br](http://www.buscarcep.com.br/)'s **[webservice](http://www.buscarcep.com.br/?secao=webservice)**. This seems to be the most comprehensive service between those are being listed in this issue.

There is the [ViaCEP](http://viacep.com.br/) webservice to returning address and IBGE code for a given CEP.

The [byJG](http://www.byjg.com.br)'s [webservice](http://www.byjg.com.br/site/xmlnuke.php?xml=onlinecep) returns CEP values for adresses.

An alternative would be parsing the [IBGE's query pages](http://www.ibge.gov.br/home/geociencias/areaterritorial/area.shtm)...

I would suggest to use the BuscarCep.com.br's webservice. But it is NOT a free service! Well, **maybe** a solution is combine ViaCEP and byJG.

**Comment by tmpsantos** [comment]
Even if the service for querying the zip code is free for use, I'm not sure if we can use the data they provide. ViaCEP for instance has no statement about the usage policy and licensing of their data. :(

But at the moment, we don't parse the street names from the IBGE PDFs. I think this is pretty much impossible due to low resolution of most of the images and randomness of how these names appears on the PDF.

Is that what you have in mind?

**Comment by alexandre-mbm** [comment]
This data will not go to OpenStreetMap. Maybe be stay longer clear if the downloader was a small project separate. What I have in mind is not parse street names from the IBGE PDFs. It download these PDFs easy:

``` bash
$ program.py --query "São Paulo"
AM  1303908     São Paulo de Olivença
RN  2412609     São Paulo do Potengi
SP  3550308     São Paulo
RS  4319307     São Paulo das Missões
$ program.py --download "3550308"
```

And adaptations in IBGETools for this be util.

**Comment by tmpsantos** [comment]
Ah, I see now. This is a good idea, I will have a look. Thanks!

**Comment by tmpsantos** [comment]
@alexandre-mbm check this out: http://www.rais.gov.br/mun_mg.asp

**Comment by alexandre-mbm** [comment]
Initially, I can compile CSV files in a "db" directory for you. With the script respective. I do?

I wonder if you would use my work or if you're already working on this. @tmpsantos, if we did the same thing at the same time would be a waste of time. I would in a small manager in Python. Simplicity and clean code.

**Comment by tmpsantos** [comment]
If you could compile a .csv of the codes and the city name for me that would be a great contribution!

**Comment by alexandre-mbm** [comment]
I'll do. Give me a few hours.

**Comment by alexandre-mbm** [comment]
I intend to make the code more clean and organized at next commits. I intend to resolve the issue. But now I'll rest a break.

You can accept the pull request as it is. Please let me know if you start working from it.

**Comment by tmpsantos** [comment]
Thanks a lot for compiling all the city codes and cities. Now that the tool is working fine, I'm using the .csv you compiled as input for a shell script processing the images batches by state.
