### ISSUE TITLE
Pegando somente partes de uma cidade grande

### ISSUE THREAD

**Issue by jgpacker** [tmpsantos/IBGETools#5]
Sei que o programa é bem novo, e não tem urgência o que vou pedir, mas quero deixar registrado.

Quando se tem uma cidade Grande, fica inviável abrir ela inteira no JOSM, tendo que usar o programa só em parte dela. O problema é que é difícil achar as partes certas para mapear uma certa porção da cidade, tendo que manualmente abrir os documentos entre muitos pra ver se é o que está sendo procurado.

A minha sugestão é: dado uma _bounding box_, só crial o KML dos documentos que estão dentro (mesmo que parcialmente) desta _bounding box_.

Abs,
João

**Comment by alexandre-mbm** [comment]
Pelo que entendi, o autor está trabalhando para que o `ibge_kml_maker.py` não precise ser usado rotineiramente. Está montando um servidor de _tiles_ que poderão ser importados no JOSM, dispensando que o mapeador faça download e transformação de arquivos do IBGE.

**Comment by tmpsantos** [comment]
O Alexandre está certo, a idéia é ter todos os tiles de todas as cidades online. Mas ainda vai demorar um pouco até chegarmos lá. :)

A combinação JOSM + PicLayer não escala. Gasta muita memória: até com Pará de Minas que é relativamente pequena o JOSM capota.

A solução é rodar o próprio servidor de tiles localmente até conseguirmos ter tudo na web. Vou deixar esta issue aberta até eu publicar o código do gerador de tiles, só tou acertando alguns detalhes.

**Comment by tmpsantos** [comment]
Vou fechar este bug, o script agora tá rodando muito bem em cidades de qualquer tamanho. Nos meus testes aqui, uma cidade como Belo Horizonte passa em 10 minutos, então acho desnecessário o bounding box.

**Comment by alexandre-mbm** [comment]
Você ainda tem planos de prover os _tiles_?

**Comment by tmpsantos** [comment]
@alexandre-mbm tá acompanhando a lista OSM BR mais não? :)

http://tiles.tmpsantos.com.br/ e dá um zoom em MG

**Comment by alexandre-mbm** [comment]
Eu nunca fui cadastrado lá. Apenas dei umas olhadas no histórico.

Qual seria uma região para eu ver, nesse mapa?

**Comment by tmpsantos** [comment]
@alexandre-mbm aaah, então foi malz :)

Mas então, tem este mapa web, mas o legal mesmo é adicionar uma layer TMS no JOSM para quem tem interesse em mapear mais rápido.

A lista das cidades já processadas está aqui, com nomes, graças ao .csv:
http://tiles.tmpsantos.com.br/cities.txt

**Comment by alexandre-mbm** [comment]
:+1:
