### ISSUE TITLE
Erro ao processar largura

### ISSUE THREAD

**Issue by vgeorge** [tmpsantos/IBGETools#6]
Olá,

Instalei as dependências seguindo o README e instalei também o python-pypdf.

Tentei rodar:

```
../ibge_kml_maker.py ../../../data/mapas_de_setores_censitarios/3147105/MSU/ > out.kml 
```

E aconteceu o seguinte erro:

``` python
Traceback (most recent call last):
  File "../ibge_kml_maker.py", line 78, in <module>
    Main()
  File "../ibge_kml_maker.py", line 64, in Main
    ibge_map = GetMapFromPath(map_path)
  File "../ibge_kml_maker.py", line 11, in GetMapFromPath
    ibge_map = MapFactory(map_path)
  File "/home/vgeorge/src/IBGETools/IBGETools/Map.py", line 279, in MapFactory
    return MapA4Landscape(_MakePPMImage(width, height, obj.get_data()))
  File "/home/vgeorge/src/IBGETools/IBGETools/Map.py", line 240, in _MakePPMImage
    image = Image()
  File "/usr/lib/python2.7/dist-packages/wand/image.py", line 391, in __init__
    repr(width))
TypeError: width must be a natural number, not None
```

Alguma idéia do que pode ser o problema?

Obrigado, Vitor

**Comment by alexandre-mbm** [comment]
Testei em Ubuntu 12.04.4 LTS. Para isso, precisei instalar o [Wand](https://github.com/dahlia/wand) com `pip install Wand`. Usei o `python-tesseract_0.7-1.4_i386.deb`. 

A execução foi demorada mas não disparou erros. Gerou o XML.

Será que você não tem arquivos corrompidos?

@tmpsantos, faço _pull request_ com README.md contendo instruções para 12.04?

**Comment by vgeorge** [comment]
Estou usando o Ubuntu 13.04. Instalei o pip, mas ele diz que o Wand já está disponível. Também baixei de novo os arquivos, e o erro continua igual.

**Comment by tmpsantos** [comment]
Tente rodar com a última versão no IBGETools, acabei de atualizar e fazer algumas mudanças. Mas a principio deveria funcionar com a versão antiga.

Estou rodando num Ubuntu 13.10 64-bits. Segue as versões das minhas dependencias (a única que não vem no repositorio do Ubuntu é o python-tesseract):

```
python-tesseract 0.8-1.8
python-wand 0.3.2-1
python-pdfminer 20110515+dfsg-1
```

Mas sinceramente não acho que seja necessário a última versão. O Alexandre rodou até no 12.04!

Se continuar falhando na versão nova do scipt, coloque um print na variável `map_path` antes de chamar o `_MakePPMImage` e veja qual PDF que está falhando. Tente abrir no evince para testar, pode ser que o PDF esteja corrompido.

**Comment by alexandre-mbm** [comment]
@tmpsantos, já que você não me respondeu (acima), e também tem o _pull request_ da _issue_ #4, meu, sem resposta (aceitação ou negação), agora pergunto-lhe: 

Está implícito que eu devo fazer os _pull requests_ que me derem na telha e, se eles tiverem de ser aceitos, serão? Ou você não está aberto a _pull requests_?

Eu peço que você negue o que tiver de ser negado. Você não tem de aceitar. Um _pull request_ é sempre uma "sugestão", ainda que alguma vez seja também correção. Peço-lhe algum comentário.

**Comment by tmpsantos** [comment]
@alexandre-mbm foi malz, acho que na correria pulei a pergunta.

Repondendo: Acho melhor não. Sinceramente não quero suportar oficialmente nenhuma versão abaixo do 13.10 pelo simples fato que não tenho como testar e o tempo para manter. Claro que o projeto é aberto, então as pessoas são livres para inclusive criar pacotes, versões alternativas, tutoriais, etc para outras versões do Ubuntu.

Quanto ao PR #4 ainda não tive tempo de olhar. Sei que é frustrante a demora, mas meu tempo tá bem corrido. :( Minha prioridade atual é deixar a geração de tiles usável e gerar os tiles que o pessoal pediu na ML.

**Comment by tmpsantos** [comment]
Quanto a fazer PR aleatórios, fique à vontade. Todo projeto open source funciona assim, mas tenha em mente que meu trabalho aqui é voluntário e vou ver os PRs quando der tempo.

**Comment by vgeorge** [comment]
@tmpsantos Dei um git pull, mas o problema continua.

Rodei o comando:

```
../ibgetools --tiles --id parademinas ../../../data/mapas_de_setores_censitarios/3147105/MSU
```

Este foi o resultado:

``` python
Traceback (most recent call last):
  File "../ibgetools", line 125, in <module>
    Main()
  File "../ibgetools", line 109, in Main
    ibge_map = GetMapFromPath(map_path)
  File "../ibgetools", line 27, in GetMapFromPath
    ibge_map = MapFactory(map_path)
  File "/home/vgeorge/src/IBGETools/IBGETools/Map.py", line 325, in MapFactory
    return map_class(_MakePPMImage(width, height, obj.get_data()), map_path)
  File "/home/vgeorge/src/IBGETools/IBGETools/Map.py", line 269, in _MakePPMImage
    image = Image()
  File "/usr/lib/python2.7/dist-packages/wand/image.py", line 391, in __init__
    repr(width))
TypeError: width must be a natural number, not None
```

**Comment by vgeorge** [comment]
O problema era o Wand. A versão que o apt-get instalou para mim é a 0.2.3-1.

Fiz a remoção, instalei via pip e deu certo.

Obrigado!

**Comment by alexandre-mbm** [comment]
@tmpsantos, eu acho que você pode **declarar não suportar** mas exibir instruções de instalação para outras plataformas ou versões de sistema operacional. Sendo só uma questão de recolher cumulativamente as dicas. @vgeorge só conseguiu usando `pip`, dica que eu trouxe do 12.04.
