### ISSUE TITLE
Erro no parser para cidade 3526902 (Limeira/SP)

### ISSUE THREAD

**Issue by rafaeletc** [tmpsantos/IBGETools#8]
Consegui gerar tiles e kml para cidades vizinha (3512407 e 3521408), mas quando rodo o script para Limeira recebo o seguinte erro: 

```
limeira [Error] Could not parse: /home/rafael/Documents/3526902/MSU/352690205000039/A4/352690205000039.pdf
```

Para mim o cabeçalho dos arquivos são idênticos ao das outras cidades, já teve algum problema parecido?

Aproveitando, parabéns pelo trabalho!

**Comment by tmpsantos** [comment]
Já aconteceu sim. Por algum motivo, algumas cidades de SP estão com os PDFs mal renderizados.

Acontece duas coisas:
- Eles não seguem os mesmos padrões de margem.
- As coordenadas superiores ficam cortadas, então o OCR não consegue ler.

Eu tenho um hackzinho aqui que pode te ajudar. Eu implementei detecção de margem ao invés de ter os valores hardcoded. Só testar aqui e te passo o link.

**Comment by tmpsantos** [comment]
@rafaeletc tenta este branch aqui que vai parsear quase tudo (~90%), cheguei a testar aqui.

https://github.com/tmpsantos/IBGETools/tree/sp-limeira

**Comment by alexandre-mbm** [comment]
Pode fazê-lo com esses comandos:

``` bash
git remote add IBGETools https://github.com/tmpsantos/IBGETools.git
git remote update
git checkout -b sp-limeira IBGETools/sp-limeira
```

**Comment by tmpsantos** [comment]
Arrumado na última versão.
